# Generated by Django 2.0.6 on 2018-09-11 14:30

from django.db import migrations, models
import talk2x.validators


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunch',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[talk2x.validators.validate_code_mail], verbose_name='email address'),
        ),
    ]
