# Generated by Django 2.0.6 on 2018-09-11 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0002_auto_20180911_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunch',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lunch',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talk2x.Restaurant'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
