# Generated by Django 2.0.6 on 2018-09-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0003_auto_20180911_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meaning_of_life',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
