# Generated by Django 2.0.6 on 2018-09-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0004_auto_20180911_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='coupon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
