# Generated by Django 2.0.6 on 2018-09-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0006_auto_20180911_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default='moritz', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
