# Generated by Django 2.0.6 on 2018-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0007_auto_20180912_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunch',
            name='name',
        ),
        migrations.AlterField(
            model_name='lunch',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='no',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street',
            field=models.CharField(max_length=20),
        ),
    ]
