# Generated by Django 2.0.6 on 2018-09-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0008_auto_20180913_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=30),
        ),
    ]
