# Generated by Django 2.0.6 on 2018-09-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0009_auto_20180913_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurelunch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
