# Generated by Django 2.1.1 on 2018-09-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0010_futurelunch_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availabilty',
            field=models.CharField(blank=True, choices=[('MONDAY', 'monday'), ('TUESDAY', 'tuesday'), ('WEDNESDAY', 'wednesday'), ('THURSDAY', 'thursday'), ('FRIDAY', 'friday'), ('EVERYDAY', 'everyday')], max_length=10, null=True),
        ),
    ]
