# Generated by Django 2.1.1 on 2018-09-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0011_user_availabilty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_to_email',
            field=models.BooleanField(default=True),
        ),
    ]
