# Generated by Django 2.1.1 on 2018-09-28 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import talk2x.validators


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0013_auto_20180923_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
        migrations.AlterField(
            model_name='futurelunch',
            name='date',
            field=models.DateField(validators=[talk2x.validators.validate_lunch_date]),
        ),
        migrations.AlterField(
            model_name='futurelunch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talk2x.Restaurant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
