# Generated by Django 2.1.1 on 2018-10-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0014_auto_20180928_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_tc',
            field=models.BooleanField(default=False),
        ),
    ]
