# Generated by Django 2.1.1 on 2018-10-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0015_user_accepted_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='meaning_of_life',
            field=models.CharField(default='meaning of life', max_length=100),
        ),
    ]
