# Generated by Django 2.1.1 on 2018-10-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0016_auto_20181008_1410'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='futurelunch',
            unique_together={('user', 'date')},
        ),
    ]
