# Generated by Django 2.1.1 on 2018-10-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0017_auto_20181016_0854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='futurelunch',
            unique_together=set(),
        ),
    ]
