# Generated by Django 2.1.1 on 2018-10-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk2x', '0018_auto_20181016_0911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='futurelunch',
            unique_together={('user', 'date')},
        ),
    ]
