"""
Django settings for os_1 project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from celery.schedules import crontab
from datetime import date
#import djcelery
#djcelery.setup_loader()



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tceawen-!)jijo-_+oe^&h&2=8-0-q(cx7q%4qz&)^=7#w#*a0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '109.94.110.10', 'talk2x.com', '127.0.0.1', 'www.talk2x.com']


# Application definition

INSTALLED_APPS = [
#    'social_django',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'talk2x.apps.Talk2XConfig',
#    'celery',
    'djcelery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'os_1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'os_1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
#    'social_core.backends.open_id.OpenIdAuth',
#    'social_core.backends.google.GoogleOpenId',
#    'social_core.backends.google.GoogleOAuth2',
#    'social_core.backends.google.GoogleOAuth',
#    'social_core.backends.twitter.TwitterOAuth',
#    'social_core.backends.yahoo.YahooOpenId',
    'django.contrib.auth.backends.ModelBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/uploads/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



AUTH_USER_MODEL = 'talk2x.User'

LOGIN_REDIRECT_URL = '/home'
LOGIN_URL = '/home'
LOGOUT_REDIRECT_URL = '/'

DAYS = [1, 2, 3, 4, 5]

CELERY_BROKER_URL = 'amqp://'
CELERY_RESULT_BACKEND = 'djcelery.backends.database:DatabaseBackend'
#CELERY_RESULT_BACKEND = 'rpc://'
CELERY_TIMEZONE = 'Europe/Berlin'
CELERY_IMPORTS = ('talk2x.tasks')
CELERYBEAT_SCHEDULE = {

    'match_user': {
        'task': 'talk2x.tasks.create_matches',
        'schedule' : crontab(hour=12, minute=0, day_of_week=DAYS),
        'args' : [date.today()]
    },

    'delete_future_lunches': {
        'task': 'talk2x.tasks.delete_future_lunch',
        'schedule' : crontab(hour=13, minute=0, day_of_week=DAYS)
    },

    'send_feedback': {
        'task' : 'talk2x.tasks.feedback',
        'schedule' : crontab(hour=15, minute=0, day_of_week=DAYS)
    },


}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

EMAIL_HOST_USER = 'hi@talk2x.com'
EMAIL_HOST_PASSWORD = 'Talk0396!'
DEFAULT_FROM_EMAIL = 'hi@talk2x.com'
SERVER_EMAIL = 'hi@talk2x.com'
